<?php declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;
use Siteation\StoreUsps\ViewModel\StoreUsps;

/** @var ViewModelRegistry $viewModels */
/** @var Template $block */
/** @var Escaper $escaper */

/** @var StoreUsps $storeUsps */
$storeUsps = $viewModels->require(StoreUsps::class);

$usps = $storeUsps->getUsps();

if (count($usps) === 0) {
    return '';
}
?>

<?php foreach ($usps as $index => $usp): ?>
    <div class="shrink-0 lg:shrink-1"><?= $escaper->escapeHtml($usp, ['a', 'strong', 'em', 'br']); ?></div>
<?php endforeach; ?>
