<?php declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;
use Siteation\StoreUsps\ViewModel\StoreUsps;

/** @var ViewModelRegistry $viewModels */
/** @var Template $block */
/** @var Escaper $escaper */

/** @var StoreUsps $storeUsps */
$storeUsps = $viewModels->require(StoreUsps::class);

$usps = $storeUsps->getUsps();

if (count($usps) === 0) {
    return '';
}

?>

<div class="bg-container-lighter mb-2 py-4">
    <div class="container">
        <div id="header-usps" class="usps-marquee lg:not-usps-marquee flex lg:block overflow-hidden select-none text-sm">
            <div class="usps-group min-w-full shrink-0 flex justify-around items-center lg:justify-start lg:flex-wrap lg:shrink-1 lg:gap-x-4 lg:gap-y-2">
                <?= $block->getChildHtml('') ?>
            </div>
            <div
                class="usps-group min-w-full shrink-0 flex justify-around items-center lg:hidden"
                aria-hidden="true"
            >
                <?= $block->getChildHtml('') ?>
            </div>
        </div>
    </div>
</div>
