<?php declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;
use Siteation\StoreInfoUsps\ViewModel\StoreInfoUsps;

/** @var ViewModelRegistry $viewModels */
/** @var Template $block */
/** @var Escaper $escaper */

/** @var HeroiconsOutline $heroIcons */
$heroIcons = $viewModels->require(HeroiconsOutline::class);

/** @var StoreInfoUsps $storeUsps */
$storeUsps = $viewModels->require(StoreInfoUsps::class);

$usps = $storeUsps->getProductUsps();

if (count($usps) === 0) {
    return '';
}
?>

<section aria-label="<?= $escaper->escapeHtml(__('Our Unique Selling Points')) ?>">
    <ul class="usps space-y-2 font-semibold">
        <?php foreach ($usps as $usp): ?>
            <li class="flex gap-2 items-center">
                <?= $heroIcons->checkCircleHtml('text-green-500', 24, 24, ['aria-hidden' => 'true']) ?>
                <?= $escaper->escapeHtml($usp, ['a', 'strong', 'em', 'br']); ?>
            </li>
        <?php endforeach; ?>
    </ul>
</section>
