<?php declare(strict_types=1);

/**
 * @author Siteation (https://siteation.dev/)
 * @copyright Copyright 2023 Siteation (https://siteation.dev/)
 * @license MIT
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;
use Siteation\StoreInfoUsps\ViewModel\StoreInfoUsps;

/** @var ViewModelRegistry $viewModels */
/** @var Template $block */
/** @var Escaper $escaper */

/** @var HeroiconsOutline $heroIcons */
$heroIcons = $viewModels->require(HeroiconsOutline::class);

/** @var StoreInfoUsps $storeUsps */
$storeUsps = $viewModels->require(StoreInfoUsps::class);

$usps = $storeUsps->getFooterUsps();

if (count($usps) === 0) {
    return '';
}

?>

<section
    class="border-t border-container-darker bg-container-darker py-4"
    aria-label="<?= $escaper->escapeHtml(__('Our Extra Selling Points')) ?>"
>
    <div class="top-container container">
        <ul
            class="usps grid gap-x-8 gap-y-2 place-content-center lg:flex lg:flex-wrap lg:justify-start"
            x-data="uspsCarousel"
            @resize.window.debounce="checkIsMobileResolution"
            @visibilitychange.window.debounce="checkIsMobileResolution"
        >
            <?php
                $uspsStartIndex = 1;
                foreach ($usps as $usp):
            ?>
                <li
                    class="inline-flex gap-2 justify-center items-center row-start-1 col-start-1 lg:shrink-1 lg:justify-start
                        opacity-0 lg:opacity-100 aria-[current=true]:opacity-100 transition-opacity"
                    data-index="<?= /** @noEscape */ $uspsStartIndex ?>"
                    :aria-current="activeUspsClass"
                >
                    <svg
                        viewBox="0 0 24 24"
                        xmlns="http://www.w3.org/2000/svg"
                        width="20"
                        height="20"
                        stroke="currentColor"
                        class="text-primary"
                        aria-hidden="true"
                    >
                        <use href="<?= $block->getViewFileUrl('Siteation_StoreInfoUsps::images/usps.svg'); ?>#<?= $escaper->escapeHtml($usp['icon_name']); ?>" />
                    </svg>
                    <?= $escaper->escapeHtml($usp['content'], ['a', 'strong', 'em', 'br']); ?>
                </li>
            <?php
                $uspsStartIndex++;
                endforeach;
            ?>
        </ul>
    </div>
</section>
